export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILD = 'VERIFY_EMAIL_FAILD'

export const VERIFIED_ERROR = 'VERIFIED_ERROR'

export const ADD_BALENCE = 'ADD_BALENCE'
export const UPDATE_USER = 'UPDATE_USER'

export const SELECT_DIRECTORIES = 'SELECT_DIRECTORIES'